config/routes.rb
Rails.application.routes.draw do
  root 'pages#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  
  get 'movies' => 'movies#list', as: 'movies'
  get '/movies/:id', to: 'movies#show', as: 'show_movie'
  
  get 'reviews' => 'reviews#show', as: 'reviews'
  get 'reviews/new/:id' => 'reviews#new', as: 'new_review'
  post 'reviews/create/:id' => 'reviews#create', as: 'create_review'
end

app/views/pages/about.html.erb
<h1>About MovieGuru</h1>
<p>MovieGuru is a professional-grade movie review site built for the TCI coding challenge.</p>
<h3>Features</h3>
<ul>
	<li>Gets movies from The Movie Database</li>
	<li>Allows users to add ratings to movies in the database</li>
	<li>So much more!</li>
</ul>
<p>You can view this project's source code on GitHub by <a href="https://github.com/JamsheedMistri/MovieGuru" target="_blank">clicking here</a>!</p>

app/views/pages/index.html.erb
<!-- Sort pagination -->
<nav aria-label="Page navigation example">
	<ul class="pagination" id="sort-by-pagination">
		<span id="sort-by-label">Sort By:</span>
		<li class="page-item"><%= link_to "None", home_path(sort: "none"), {class: "#{active("none")} page-link text-dark", id: 'sort-by-first-link'} %></li>
		<li class="page-item"><%= link_to "Title", home_path(sort: "title"), class: "#{active("title")} page-link text-dark" %></li>
		<li class="page-item"><%= link_to "Release Date", home_path(sort: "release_date"), class: "#{active("release_date")} page-link text-dark" %></li>
		<li class="page-item"><%= link_to "Genre", home_path(sort: "genre"), class: "#{active("genre")} page-link text-dark" %></li>
	</ul>
</nav>

<div class="row">
	<div class="col-md-8">
		<!-- Print each movie -->
		<% @movies.each do |movie| %>
			<div class="card flex-row flex-wrap">
				<div class="card-header border-0 col-md-4">
					<img src="<%= $images_url + movie.poster_path %>" class="movie-poster">
					<h1 class="average-rating text-dark"><%= print_average_rating(movie) %></h1>
				</div>
				<div class="card-block px-2 col-md-8">
					<h4 class="card-title"><%= movie.title %></h4>
					<p class="card-text">
						<b>Release Date</b>: <%= format_date(movie.release_date) %>
						<br>
						<b>Genres</b>:
						<% movie.genres.each do |genre| %>
							<a class="badge badge-warning"><%= genre.name %></a>
						<% end %>
					</p>
					
					<% movie.reviews.each do |review| %>
						<p>
							<%= print_rating(review.rating) %>
							&nbsp;&nbsp;&nbsp;&nbsp;
							<% if review.comment != "" %>
								"<%= review.comment %>" - 
							<% end %>
							<b><%= review.email %></b>
						</p>
					<% end %>

					<% if movie.reviews.length == 0 %>
						<p>There are currently no ratings for <b><%= movie.title %></b> on MovieGuru. Be the first to add one by clicking below!</p>
					<% else %>
						<%= link_to 'View More', show_movie_path(movie.id), class: "btn btn-dark" %>
					<% end %>
					<%= link_to 'Leave a Review', new_review_path(movie.id), class: "btn btn-warning" %>
				</div>
			</div>
		<% end %>
	</div>

	<!-- Right column -->
	<div class="col-md-4">
		<!-- Print the recent reviews -->
		<div class="card">
		  <div class="card-body">
		    <h4 class="card-title">Recent Reviews</h4>
		    <% @recent_reviews.each do |review| %>
				<p>
					<%= print_rating(review["rating"]) %>
					&nbsp;&nbsp;&nbsp;&nbsp;
					<% if review["comment"] != "" %>
						"<%= review["comment"] %>" - 
					<% end %>
					<b><%= review["email"] %></b><br>
					<span class="recent-reviews-movie"><%= review["movie_obj"].title %></span>
				</p>
			<% end %>
		    <div class="text-right"><%= link_to 'View All Reviews', reviews_path %></div>
		  </div>
		</div>
		<!-- Print the recent movies -->
		<div class="card">
		  <div class="card-body">
		    <h4 class="card-title">Recent Movies</h4>
		    <% @recent_movies.each do |movie| %>
				<p>
					<span class="align-title-left"><%= movie.title %></span>
					<span class="align-rating-right"><%= print_average_rating(movie) %></span>
					<div style="clear: both;"></div>
				</p>
			<% end %>
		    <div class="text-right"><%= link_to 'View All Movies', movies_path %></div>
		  </div>
		</div>
	</div>
</div>