config/routes.rb
Rails.application.routes.draw do
  root 'pages#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  
  get 'movies' => 'movies#list', as: 'movies'
  get '/movies/:id', to: 'movies#show', as: 'show_movie'
  
  get 'reviews' => 'reviews#show', as: 'reviews'
  get 'reviews/new/:id' => 'reviews#new', as: 'new_review'
  post 'reviews/create/:id' => 'reviews#create', as: 'create_review'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # Show all reviews
  def show
    # Get all review objects
    @review_objects = Review.all

    # Convert array of reviews to array of hashes with corresponding review data (so we can modify before sending to view)
    @reviews = []
    @review_objects.each do |object|
      @reviews.push(object.attributes)
    end

    # For each review, find the movie it belongs to and add a reference to it in the hash
    @reviews.each do |review|
      review["movie_obj"] = Tmdb::Movie.detail(review["movie"])
    end

    # Before sending reviews to the view, ensure that the newest display first
    @reviews.reverse!
  end
  
  # Create a new review
  def new
    # Get the movie object that corresponds to the new review form for displaying on the view
    @movie = Tmdb::Movie.detail(params[:id])

    # Leave a title corresponding to the movie title being reviewed
    @title = "Leave a Review | " + @movie.title

    # If there are any errors from the previous attempt, send them to the view
    @errors = session[:errors]
    session[:errors] = nil
  end

  # Post method to create a review from the new review form
  def create
    # Get the permitted parameters using this helper method
    review_params = raw_params

    # Add the movie ID and the date to the new review before creating it
    review_params[:movie] = params[:id]
    review_params[:date] = DateTime.now.strftime('%Y-%m-%d')

    # Create the new review based on the hash
    @review = Review.new(review_params)

    # Attempt to save the review
    if (@review.save)
      # If the review saves successfully, redirect to the movie that it reviewed
      redirect_to show_movie_path(params[:id])
    else
      # If the review did not save successfully, send the error messages to the form again
      session[:errors] = @review.errors.full_messages
      redirect_to new_review_path(params[:id])
    end
  end

  # Private helper method to get permitted parameters for a new review
  private def raw_params
    params.require(:review).permit(:email, :rating, :comment)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/new.html.erb
<!-- Print out any errors if there was an issue with the previous sumbission -->
<% if @errors != nil && @errors.any? %>
	<% @errors.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end %>
<h1>Leave a Review</h1>
<div class="row">
	<div class="col-md-8">
		<!-- For for leaving a review -->
		<%= form_for :review, url: create_review_path do |f| %>
			<p>
				<%= f.label :email %><br>
				<%= f.text_field(:email, class: 'form-control') %>
			</p>

			<p>
				<%= f.label :rating %> (out of 5)<br>
				<%= f.select(:rating, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]], {}, class: "form-control" ) %>
			</p>

			<p>
				<%= f.label :comment %> (optional)<br>
				<%= f.text_area(:comment, class: 'form-control') %>
			</p>

			<p>
				<%= f.submit("Submit Review", class: 'btn btn-warning') %>
			</p>
		<% end %>
	</div>
	<!-- Display preview of the movie being reviewed -->
	<div class="col-md-4">
		<div class="card">
		  <img class="card-img-top" src="<%= $images_url + @movie.poster_path %>">
		  <div class="card-body">
		  	<!-- Movie title -->
		    <h4 class="card-title"><%= @movie.title %></h4>
		    <!-- Movie info -->
			<p class="card-text">
				<b>Release Date</b>: <%= format_date(@movie.release_date) %>
				<br>
				<b>Genres</b>:
				<% @movie.genres.each do |genre| %>
					<a class="badge badge-warning"><%= genre.name %></a>
				<% end %>
			</p>
		  </div>
		</div>
	</div>
</div>

app/views/reviews/show.html.erb
<h1>All Reviews</h1>
<!-- Print out all reviews in full -->
<% @reviews.each do |review| %>
	<div class="card">
	  <div class="card-body">
	    <h4 class="card-title"><%= review["movie_obj"].title %></h4>
	    <h5 class="card-title"><%= print_rating(review["rating"]) %></h5>
	    <p>
	    	<b>Creator</b>: <%= review["email"] %>
	    	<br>
	    	<b>Date</b>: <%= format_date(review["date"]) %>
	    	<% if review["comment"] != "" %>
	    		<br>
	    		<b>Comment</b>: <%= review["comment"] %>
	    	<% end %>
	    </p>
	    <%= link_to 'Show all reviews for <b>'.html_safe + review["movie_obj"].title + '</b>'.html_safe, show_movie_path(review["movie"]), class: "btn btn-warning"%>
	  </div>
	</div>
<% end %>