config/routes.rb
Rails.application.routes.draw do
  root 'pages#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  
  get 'movies' => 'movies#list', as: 'movies'
  get '/movies/:id', to: 'movies#show', as: 'show_movie'
  
  get 'reviews' => 'reviews#show', as: 'reviews'
  get 'reviews/new/:id' => 'reviews#new', as: 'new_review'
  post 'reviews/create/:id' => 'reviews#create', as: 'create_review'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title == nil ? "MovieGuru" : @title + " | MovieGuru"  %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
      <div class="container">
        <%= link_to "MovieGuru", home_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Home", home_path, class: "#{cp(home_path)} nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Movies", movies_path, class: "#{cp(movies_path)} nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Reviews", reviews_path, class: "#{cp(reviews_path)} nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, class: "#{cp(about_path)} nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container main-content-container">
      <%= yield %>
    </div>
  </body>
</html>